[phases.setup]
nixPkgs = ["php", "phpPackages.pdo_mysql"]

[phases.build]
cmds = ["php -r \"echo 'PDO MySQL: ' . (extension_loaded('pdo_mysql') ? 'YES' : 'NO') . PHP_EOL;\""]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."