[phases.setup]
nixPkgs = ["php85", "php85Extensions.pdo_mysql", "php85Extensions.pdo", "php85Extensions.mysqli", "php85Extensions.mbstring", "php85Extensions.openssl"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."